version: '3.8'
services:
  db:
    container_name: embarca_city_searcher_sgbd
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  embarca_city_searcher:
    container_name: embarca_city_searcher_app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid &&
          bundle exec rails db:reset &&
          bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - app-storage:/rails/storage
    ports:
      - "3000:3000"
    depends_on:
      - db
      
volumes:
  postgres_data: {}
  app-storage: {}