default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "postgres" %>
  host: db

development:
  <<: *default
  database: embarca_city_searcher_development

test:
  <<: *default
  database: embarca_city_searcher_test

production:
  <<: *default
  database: embarca_city_searcher_production
  username: embarca_city_searcher
  password: <%= ENV['EMBARCA_CITY_SEARCHER_DATABASE_PASSWORD'] %>
